### ISSUE TITLE
Support for download status bars

### ISSUE THREAD

**Issue by rugk** [tdebaets/downloadscontextmenu#2]
Could you somehow add the support for add-ons which show the downloads in status bars. E.g. [Download Manager S3](https://addons.mozilla.org/de/firefox/addon/s3download-statusbar/) or  [Download Status Bar](https://addons.mozilla.org/en-US/firefox/addon/download-status-bar/).

As for Download Manager S3 - [did you answered the developer to his questions](https://addons.mozilla.org/de/firefox/addon/downloads-context-menu/reviews/662710/)?

**Comment by tdebaets** [comment]
I worked together with the author of Download Manager S3 to provide such support there, and this is present in the latest versions of Download Manager S3 and Downloads Context Menu.

About support in other add-ons: a public API is now present in my add-on, but so far, only Download Manager S3 is using it. It is up to the authors of these other add-ons to integrate the context menu in their add-on.
