### ISSUE TITLE
Send to and Open with Context menu not working

### ISSUE THREAD

**Issue by MacgyverJohnson** [tdebaets/downloadscontextmenu#3]
Hi there dev,
Your addon is awesome and perfectly complements Download manage(S3)....all of the options work except send to and open with context menu ....they wont load at all...any way to give u some logs....ff console doest show any thing :(....
![context menu](https://cloud.githubusercontent.com/assets/17729946/15115361/67b2540a-1620-11e6-93c5-2509d05c81c5.gif)
@tdebaets

**Comment by MacgyverJohnson** [comment]
:(   without Download manager (S3) it seems to be working.....any way to fix it?.......its even working from downloads side panel {using omnisidebar } using firefox 46.0.1
tried 3 more things
1)changed max firefox version from 39 to 47 in install.rdf
2)used an older version od downloads manager (S3)....4.02 which was updated 2016.01
3)run firefox with admin privileges 
@tdebaets

**Comment by tdebaets** [comment]
As the menus work fine in the standalone case, I think that this is something for the developer of Download Manager S3 to look into. I suggest that you report this to him. Closing this issue.
